### ISSUE TITLE
Cannot use variables where one of the keys has a dash in it.

### ISSUE THREAD

**Issue by Fuitad** [nicoSWD/php-rule-parser#3]
See the following test (which fails currently) for an example. Not sure if it's work-as-design or not.

Btw, awesome project!

```php
public function testArrayWithDashInKeyDoesParseCorrectly()
    {
        $this->assertTrue($this->evaluate(
            'foo-bar === [
                "foo", // This is foo
                "bar"  // And this is bar
            ]',
            ['foo-bar' => ['foo', 'bar']]
        ));
    }
```

**Comment by Fuitad** [comment]
If that's any help, I just tried the same test case but with an underscore and it does pass the test.

```php
public function testArrayWithUnderscoreInKeyDoesParseCorrectly()
    {
        $this->assertTrue($this->evaluate(
            'foo_bar === [
                "foo", // This is foo
                "bar"  // And this is bar
            ]',
            ['foo_bar' => ['foo', 'bar']]
        ));
    }
```

**Comment by nicoSWD** [comment]
Hi @Fuitad!

Thanks for your submission. This is actually by design. I tried to keep it as close to Javascript syntax as possible. Plus, if I plan on adding math equations in the future, the dash would be interpreted as minus (foo minus bar). I'm not sure if I'll ever implement this, but it crossed my mind.

However, if you're using the latest version (0.4.0 as of writing this), you can actually redefine tokens in user-land. This would allow you to do what you want.

Eg:
```php
$rule->registerToken(Tokenizer::TOKEN_VARIABLE, '[a-zA-Z_][\w-]*');
```
I hope this helps!

**Comment by cnanney** [comment]
@nicoSWD Is this no longer possible? Using `0.6.1` and there is no longer public access to the tokenizer, and all properties are private so I can't extend `Rule` and add a method to access from the container.

**Comment by nicoSWD** [comment]
@cnanney hi! It's still possible, but the approach has changed. It's now preferred to use composition instead of inheritance.

Meaning, you'd have to create your own grammar ([akin to this](https://github.com/nicoSWD/php-rule-parser/blob/master/src/Grammar/JavaScript/JavaScript.php)) and construct your own container using said grammar [like this](https://github.com/nicoSWD/php-rule-parser/blob/master/src/container.php). 

[Rule.php](https://github.com/nicoSWD/php-rule-parser/blob/master/src/Rule.php) is extendable so you should be able to override the constructor.
